# Generated by Django 4.2 on 2023-06-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalColorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='data',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('contents', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalColorApp.personalcolor')),
            ],
        ),
    ]
